### ISSUE TITLE
Does This project support multiplayer?

### ISSUE THREAD

**Issue by sana2024** [e2dk4r/Backgammon#3]
hi, I cloned this repository and as I noticed it, it's using Mirror networking, and I tested the project I couldn't see anything in the scenes related to multiplayer networking, how can I change to to a way to make it work on two devices, and if it's not why there is Mirror in the project???

**Comment by e2dk4r** [comment]
This was a student project. I was planning to networking but never got to. I got confused reading mirror networking documentation. That's the reason.

For how can you make work on two devices over the network, the only thing that I can suggest is mirror networking documentation.
